/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ccinfom.group5.esports_app.view;

import ccinfom.group5.esports_app.utils.GeneralUtil;
import javax.swing.JButton;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author Sean Kyle
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
         


        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        mainMainPanel = new JPanel();
        mainPanel = new JPanel();
        bannerPanel = new JPanel();
        jLabel1 = new JLabel();
        lowerPanel = new JPanel();
        lowerLeftPanel = new JPanel();
        menuLbl = new JLabel();
        mainViewBtn = new JButton();
        makeTransacBtn = new JButton();
        genReportsBtn = new JButton();
        exitBtn = new JButton();
        lowerRightPanel = new JPanel();
        mainViewPanel = new JPanel();
        upperMainViewPanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        String[] columnNames = {"Column1", "Column2"};
        Object[][] data = {
            {"Data1", "Data2"},
        };

        mainViewTableModel = new DefaultTableModel(data, columnNames);
        mainViewTable = new JTable();
        lowerMainViewPanel = new JPanel();
        mainViewMainMenuBtn = new JButton();
        tablesMainViewComboBox = new JComboBox<>();
        executeQueryMainViewBtn = new JButton();
        jScrollPane3 = new JScrollPane();
        queryMainViewTxtArea = new JTextArea();
        makeTransacPanel = new JPanel();
        leftMakeTransacPanel = new JPanel();
        mainMenuTransacBtn = new JButton();
        rightMakeTransacPanel = new JPanel();
        transferPlayerPanel = new JPanel();
        jScrollPane2 = new JScrollPane();
        playerTransferPlayerComboBox = new JComboBox<>();
        finalTransferPlayerBtn = new JButton();
        jScrollPane4 = new JScrollPane();
        teamTransferPlayerTransacComboBox = new JComboBox<>();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel2 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        yearTransferPlayerTxtField = new JTextField();
        monthTransferPlayerTxtField = new JTextField();
        dayTransferPlayerTxtField = new JTextField();
        jLabel8 = new JLabel();
        jCheckBox1 = new JCheckBox();
        finalDissolveTeamBtn = new JButton();
        jScrollPane6 = new JScrollPane();
        teamTransferTeamDissolveComboBox = new JComboBox<>();
        jLabel9 = new JLabel();
        yearDissolveTeamTxtField = new JTextField();
        jLabel10 = new JLabel();
        monthDissolveTeamTxtField = new JTextField();
        jLabel11 = new JLabel();
        dayDissolveTeamTxtField = new JTextField();
        jLabel12 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        teamsUpdateStatsComboBox = new JComboBox<>();
        jLabel17 = new JLabel();
        jLabel18 = new JLabel();
        teamsUpdateStatsComboBox2 = new JComboBox<>();
        jLabel19 = new JLabel();
        teamsWinnerUpdateStatsComboBox = new JComboBox<>();
        finalTeamsUpdateStatsBtn = new JButton();
        teamsUpdateStatsSpinnerModel = new SpinnerNumberModel(5000, 5000, 1000000, 5000);
        teamsUpdateStatsSpinner = new JSpinner(teamsUpdateStatsSpinnerModel);
        jLabel39 = new JLabel();
        yearTeamsUpdateStatsTxtField = new JTextField();
        jLabel40 = new JLabel();
        monthTeamsUpdateStatsTxtField = new JTextField();
        jLabel41 = new JLabel();
        dayTeamsUpdateStatsTxtField = new JTextField();
        jLabel20 = new JLabel();
        jLabel21 = new JLabel();
        sponsorAddComboBox = new JComboBox<>();
        teamSponsorAddComboBox = new JComboBox<>();
        currentTeamSponsorLbl = new JLabel();
        finalAddSponsorTeamBtn = new JButton();
        jLabel22 = new JLabel();
        addSponsorTeamSpinnerModel = new SpinnerNumberModel(20000, 20000, 1000000, 20000);
        addSponsorTeamSpinner = new JSpinner(addSponsorTeamSpinnerModel);
        jLabel23 = new JLabel();
        jLabel42 = new JLabel();
        yearSponsorAddTxtField = new JTextField();
        jLabel43 = new JLabel();
        monthSponsorAddTxtField = new JTextField();
        jLabel44 = new JLabel();
        daySponsorAddTxtField = new JTextField();
        jLabel24 = new JLabel();
        jLabel45 = new JLabel();
        yearSponsorAddTxtField1 = new JTextField();
        jLabel46 = new JLabel();
        monthSponsorAddTxtField1 = new JTextField();
        jLabel47 = new JLabel();
        daySponsorAddTxtField1 = new JTextField();
        genReportsPanel = new JPanel();
        genReportsMainMenuBtn = new JButton();
        jScrollPane5 = new JScrollPane();
        genReportsTable = new JTable();
        yearGenReportsComboBox = new JComboBox<>();
        jComboBox1 = new JComboBox<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESports Tracker - Valorant");
        setPreferredSize(new Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        mainMainPanel.setPreferredSize(new Dimension(1280, 720));
        mainMainPanel.setLayout(new CardLayout());

        mainPanel.setBackground(new Color(255, 204, 51));
        mainPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        mainPanel.setPreferredSize(new Dimension(1280, 720));
        mainPanel.setLayout(new GridBagLayout());

        bannerPanel.setBackground(new Color(51, 102, 0));

        jLabel1.setFont(new Font("Berlin Sans FB Demi", 0, 45)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("ESports Tracker - Valorant");
        jLabel1.setPreferredSize(new Dimension(1280, 720));

        GroupLayout bannerPanelLayout = new GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(bannerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        bannerPanelLayout.setVerticalGroup(bannerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(bannerPanel, gridBagConstraints);

        lowerPanel.setMinimumSize(new Dimension(400, 600));
        lowerPanel.setLayout(new GridBagLayout());

        lowerLeftPanel.setBackground(new Color(204, 204, 204));
        lowerLeftPanel.setLayout(new GridBagLayout());

        menuLbl.setFont(new Font("sansserif", 1, 24)); // NOI18N
        menuLbl.setHorizontalAlignment(SwingConstants.CENTER);
        menuLbl.setText("MENU");
        menuLbl.setPreferredSize(new Dimension(70, 28));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        lowerLeftPanel.add(menuLbl, gridBagConstraints);

        mainViewBtn.setFont(new Font("sansserif", 0, 16)); // NOI18N
        mainViewBtn.setText("Main View");
        mainViewBtn.setPreferredSize(new Dimension(135, 60));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(7, 10, 7, 10);
        lowerLeftPanel.add(mainViewBtn, gridBagConstraints);

        makeTransacBtn.setFont(new Font("sansserif", 0, 15)); // NOI18N
        makeTransacBtn.setLabel("<html><div style='text-align': center;'>Make<br>Transactions</div></html>");
        makeTransacBtn.setPreferredSize(mainViewBtn.getPreferredSize());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(7, 10, 7, 10);
        lowerLeftPanel.add(makeTransacBtn, gridBagConstraints);

        genReportsBtn.setFont(new Font("sansserif", 0, 15)); // NOI18N
        genReportsBtn.setText("Generate Reports");
        genReportsBtn.setPreferredSize(mainViewBtn.getPreferredSize());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.insets = new Insets(7, 10, 7, 10);
        lowerLeftPanel.add(genReportsBtn, gridBagConstraints);

        exitBtn.setFont(new Font("sansserif", 0, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setPreferredSize(new Dimension(72, 40));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(75, 10, 75, 10);
        lowerLeftPanel.add(exitBtn, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        lowerPanel.add(lowerLeftPanel, gridBagConstraints);

        lowerRightPanel.setBackground(new Color(0, 255, 204));

        GroupLayout lowerRightPanelLayout = new GroupLayout(lowerRightPanel);
        lowerRightPanel.setLayout(lowerRightPanelLayout);
        lowerRightPanelLayout.setHorizontalGroup(lowerRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        lowerRightPanelLayout.setVerticalGroup(lowerRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        lowerPanel.add(lowerRightPanel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        mainPanel.add(lowerPanel, gridBagConstraints);

        mainMainPanel.add(mainPanel, "mainmenu");
        mainPanel.getAccessibleContext().setAccessibleParent(mainMainPanel);

        mainViewPanel.setBackground(new Color(204, 255, 204));
        mainViewPanel.setOpaque(false);
        mainViewPanel.setPreferredSize(new Dimension(1280, 720));

        upperMainViewPanel.setBackground(new Color(204, 255, 204));
        upperMainViewPanel.setPreferredSize(new Dimension(1280, 400));

        jScrollPane1.setViewportBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new Dimension(1000, 470));
        jScrollPane1.setViewportView(mainViewTable);
        jScrollPane1.setWheelScrollingEnabled(false);

        mainViewTable.setModel(mainViewTableModel);
        mainViewTable.setPreferredSize(null);
        mainViewTable.setRequestFocusEnabled(false);
        mainViewTable.setRowSelectionAllowed(false);
        mainViewTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(mainViewTable);

        GroupLayout upperMainViewPanelLayout = new GroupLayout(upperMainViewPanel);
        upperMainViewPanel.setLayout(upperMainViewPanelLayout);
        upperMainViewPanelLayout.setHorizontalGroup(upperMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, upperMainViewPanelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        upperMainViewPanelLayout.setVerticalGroup(upperMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(upperMainViewPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 365, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lowerMainViewPanel.setBackground(new Color(204, 255, 204));
        lowerMainViewPanel.setPreferredSize(new Dimension(1124, 270));

        mainViewMainMenuBtn.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        mainViewMainMenuBtn.setText("Main Menu");
        mainViewMainMenuBtn.setPreferredSize(new Dimension(89, 30));

        tablesMainViewComBoxDefModel = new DefaultComboBoxModel<String>();
        for (String tableName : GeneralUtil.getArrayTableNames()) {
            tablesMainViewComBoxDefModel.addElement(tableName);
        }
        tablesMainViewComboBox.setModel(tablesMainViewComBoxDefModel);
        tablesMainViewComboBox.setSelectedItem("players");
        tablesMainViewComboBox.setPreferredSize(new Dimension(200, 35));

        executeQueryMainViewBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        executeQueryMainViewBtn.setText("Execute Query");

        queryMainViewTxtArea.setColumns(20);
        queryMainViewTxtArea.setRows(5);
        jScrollPane3.setViewportView(queryMainViewTxtArea);

        GroupLayout lowerMainViewPanelLayout = new GroupLayout(lowerMainViewPanel);
        lowerMainViewPanel.setLayout(lowerMainViewPanelLayout);
        lowerMainViewPanelLayout.setHorizontalGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(tablesMainViewComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 537, GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(mainViewMainMenuBtn, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE))
                    .addComponent(executeQueryMainViewBtn, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lowerMainViewPanelLayout.setVerticalGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(mainViewMainMenuBtn, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablesMainViewComboBox, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(executeQueryMainViewBtn, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        GroupLayout mainViewPanelLayout = new GroupLayout(mainViewPanel);
        mainViewPanel.setLayout(mainViewPanelLayout);
        mainViewPanelLayout.setHorizontalGroup(mainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainViewPanelLayout.createSequentialGroup()
                .addComponent(upperMainViewPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lowerMainViewPanel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        mainViewPanelLayout.setVerticalGroup(mainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainViewPanelLayout.createSequentialGroup()
                .addComponent(upperMainViewPanel, GroupLayout.PREFERRED_SIZE, 446, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lowerMainViewPanel, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainMainPanel.add(mainViewPanel, "mainview");

        makeTransacPanel.setPreferredSize(new Dimension(1280, 720));

        leftMakeTransacPanel.setBackground(new Color(204, 204, 0));

        mainMenuTransacBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        mainMenuTransacBtn.setText("Main Menu");

        GroupLayout leftMakeTransacPanelLayout = new GroupLayout(leftMakeTransacPanel);
        leftMakeTransacPanel.setLayout(leftMakeTransacPanelLayout);
        leftMakeTransacPanelLayout.setHorizontalGroup(leftMakeTransacPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(leftMakeTransacPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(mainMenuTransacBtn, GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        leftMakeTransacPanelLayout.setVerticalGroup(leftMakeTransacPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(leftMakeTransacPanelLayout.createSequentialGroup()
                .addGap(513, 513, 513)
                .addComponent(mainMenuTransacBtn, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightMakeTransacPanel.setLayout(new CardLayout());

        playersComboBoxModel = new DefaultComboBoxModel<String>();
        playerTransferPlayerComboBox.setModel(playersComboBoxModel);
        jScrollPane2.setViewportView(playerTransferPlayerComboBox);

        finalTransferPlayerBtn.setBackground(new Color(255, 0, 0));
        finalTransferPlayerBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        finalTransferPlayerBtn.setForeground(new Color(255, 255, 255));
        finalTransferPlayerBtn.setText("Transfer Player");

        teamsTransferPlayerComboBoxModel = new DefaultComboBoxModel<String>();
        teamTransferPlayerTransacComboBox.setModel(teamsTransferPlayerComboBoxModel);
        jScrollPane4.setViewportView(teamTransferPlayerTransacComboBox);

        jLabel3.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Player to Transfer");

        jLabel4.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("New Team");

        jLabel5.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Transfer Date");

        jLabel2.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Year");

        jLabel6.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Month");

        jLabel7.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Day");

        dayTransferPlayerTxtField.setToolTipText("");

        jLabel8.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Team to Dissolve");
        jLabel8.setToolTipText("");

        jCheckBox1.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setText("set to Active");
        jCheckBox1.setToolTipText("");

        finalDissolveTeamBtn.setBackground(new Color(255, 0, 0));
        finalDissolveTeamBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        finalDissolveTeamBtn.setForeground(new Color(255, 255, 255));
        finalDissolveTeamBtn.setText("Dissolve Team");

        teamsDissolveTeamComboBoxModel = new DefaultComboBoxModel<String>();
        teamTransferTeamDissolveComboBox.setModel(teamsDissolveTeamComboBoxModel);
        jScrollPane6.setViewportView(teamTransferTeamDissolveComboBox);

        jLabel9.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Year");

        jLabel10.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Month");

        jLabel11.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Day");

        dayDissolveTeamTxtField.setToolTipText("");

        jLabel12.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Dissolution Date");
        jLabel12.setToolTipText("");

        jLabel14.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Sponsor to Add");

        jLabel15.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Team");

        jLabel16.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Match Status");

        teamsUpdateStatsComboBoxModel = new DefaultComboBoxModel<String>();
        teamsUpdateStatsComboBox.setModel(teamsUpdateStatsComboBoxModel);

        jLabel17.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Team 1");

        jLabel18.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Team 2");

        teamsUpdateStatsComboBoxModel2 = new DefaultComboBoxModel<String>();
        teamsUpdateStatsComboBox2.setModel(teamsUpdateStatsComboBoxModel2);

        jLabel19.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Winner");

        teamsWinnerUpdateStatsComboBoxModel = new DefaultComboBoxModel<String>();
        teamsWinnerUpdateStatsComboBox.setModel(teamsWinnerUpdateStatsComboBoxModel);

        finalTeamsUpdateStatsBtn.setBackground(new Color(255, 0, 0));
        finalTeamsUpdateStatsBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        finalTeamsUpdateStatsBtn.setForeground(new Color(255, 255, 255));
        finalTeamsUpdateStatsBtn.setText("Finalize Match");

        jLabel39.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setText("Year");

        jLabel40.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setText("Month");

        jLabel41.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("Day");

        dayTeamsUpdateStatsTxtField.setToolTipText("");

        jLabel20.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Winner Prize");

        jLabel21.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Match Date");

        sponsorAddComboBoxModel = new DefaultComboBoxModel<String>();
        sponsorAddComboBox.setModel(sponsorAddComboBoxModel);

        teamSponsorAddComboBoxModel = new DefaultComboBoxModel<String>();
        teamSponsorAddComboBox.setModel(teamSponsorAddComboBoxModel);

        currentTeamSponsorLbl.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        currentTeamSponsorLbl.setText("Current Team has");

        finalAddSponsorTeamBtn.setBackground(new Color(255, 0, 0));
        finalAddSponsorTeamBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        finalAddSponsorTeamBtn.setForeground(new Color(255, 255, 255));
        finalAddSponsorTeamBtn.setText("Add Sponsor");

        jLabel22.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Set Contract Amount");

        jLabel23.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Start of Contract");

        jLabel42.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("Year");

        jLabel43.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("Month");

        jLabel44.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setText("Day");

        daySponsorAddTxtField.setToolTipText("");

        jLabel24.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("End of Contract");

        jLabel45.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("Year");

        jLabel46.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setText("Month");

        jLabel47.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setText("Day");

        daySponsorAddTxtField1.setToolTipText("");

        GroupLayout transferPlayerPanelLayout = new GroupLayout(transferPlayerPanel);
        transferPlayerPanel.setLayout(transferPlayerPanelLayout);
        transferPlayerPanelLayout.setHorizontalGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(GroupLayout.Alignment.TRAILING, transferPlayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(yearTransferPlayerTxtField, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(dayTransferPlayerTxtField, GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(monthTransferPlayerTxtField)))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6)
                    .addComponent(finalDissolveTeamBtn, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE))
                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalTransferPlayerBtn, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                        .addGap(161, 161, 161))
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10, GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearDissolveTeamTxtField)
                                    .addComponent(dayDissolveTeamTxtField)
                                    .addComponent(monthDissolveTeamTxtField, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(currentTeamSponsorLbl, GroupLayout.PREFERRED_SIZE, 218, GroupLayout.PREFERRED_SIZE))
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel43, GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearSponsorAddTxtField)
                                    .addComponent(daySponsorAddTxtField)
                                    .addComponent(monthSponsorAddTxtField, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel24, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel46, GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearSponsorAddTxtField1)
                                    .addComponent(daySponsorAddTxtField1)
                                    .addComponent(monthSponsorAddTxtField1, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(finalAddSponsorTeamBtn, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
                            .addComponent(addSponsorTeamSpinner, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(teamsUpdateStatsComboBox, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(teamsWinnerUpdateStatsComboBox, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(teamsUpdateStatsSpinner, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalTeamsUpdateStatsBtn, GroupLayout.PREFERRED_SIZE, 163, GroupLayout.PREFERRED_SIZE)
                            .addComponent(sponsorAddComboBox, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE))
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(teamsUpdateStatsComboBox2, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18))
                                    .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                            .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel39)
                                                .addComponent(jLabel40, GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel41))
                                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(yearTeamsUpdateStatsTxtField)
                                                .addComponent(dayTeamsUpdateStatsTxtField)
                                                .addComponent(monthTeamsUpdateStatsTxtField, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 47, Short.MAX_VALUE))
                            .addGroup(GroupLayout.Alignment.TRAILING, transferPlayerPanelLayout.createSequentialGroup()
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(teamSponsorAddComboBox, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))))))
        );
        transferPlayerPanelLayout.setVerticalGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(yearTransferPlayerTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(monthTransferPlayerTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(finalTransferPlayerBtn, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                            .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(dayTransferPlayerTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sponsorAddComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamSponsorAddComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addComponent(currentTeamSponsorLbl)
                        .addGap(8, 8, 8)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel42)
                                    .addComponent(yearSponsorAddTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel43)
                                    .addComponent(monthSponsorAddTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44)
                                    .addComponent(daySponsorAddTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel45)
                                            .addComponent(yearSponsorAddTxtField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addSponsorTeamSpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel46)
                                            .addComponent(monthSponsorAddTxtField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel47)
                                            .addComponent(daySponsorAddTxtField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(finalAddSponsorTeamBtn, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(finalDissolveTeamBtn, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel16)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(teamsUpdateStatsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(teamsUpdateStatsComboBox2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addComponent(teamsWinnerUpdateStatsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(teamsUpdateStatsSpinner, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(finalTeamsUpdateStatsBtn, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel39)
                                            .addComponent(yearTeamsUpdateStatsTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel40)
                                            .addComponent(monthTeamsUpdateStatsTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel41)
                                            .addComponent(dayTeamsUpdateStatsTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(transferPlayerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(yearDissolveTeamTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(monthDissolveTeamTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transferPlayerPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(dayDissolveTeamTxtField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(260, 260, 260))))
        );

        rightMakeTransacPanel.add(transferPlayerPanel, "card2");

        GroupLayout makeTransacPanelLayout = new GroupLayout(makeTransacPanel);
        makeTransacPanel.setLayout(makeTransacPanelLayout);
        makeTransacPanelLayout.setHorizontalGroup(makeTransacPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(makeTransacPanelLayout.createSequentialGroup()
                .addComponent(leftMakeTransacPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightMakeTransacPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        makeTransacPanelLayout.setVerticalGroup(makeTransacPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(makeTransacPanelLayout.createSequentialGroup()
                .addGroup(makeTransacPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rightMakeTransacPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftMakeTransacPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 69, Short.MAX_VALUE))
        );

        mainMainPanel.add(makeTransacPanel, "maketransac");

        genReportsMainMenuBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        genReportsMainMenuBtn.setText("Main Menu");

        genReportsTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(genReportsTable);

        yearGenReportsComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GroupLayout genReportsPanelLayout = new GroupLayout(genReportsPanel);
        genReportsPanel.setLayout(genReportsPanelLayout);
        genReportsPanelLayout.setHorizontalGroup(genReportsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(genReportsPanelLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(yearGenReportsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 912, GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(genReportsPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(genReportsMainMenuBtn, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        genReportsPanelLayout.setVerticalGroup(genReportsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, genReportsPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(genReportsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(genReportsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearGenReportsComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(genReportsMainMenuBtn, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        mainMainPanel.add(genReportsPanel, "genreports");

        getContentPane().add(mainMainPanel);
        mainMainPanel.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public CardLayout getCardLayout() {
        return (CardLayout) mainMainPanel.getLayout();
    }
    public JPanel getMainMainPanel() {
        return mainMainPanel;
    }
    public JPanel getMainPanel() {
        return mainPanel;
    }
    public JPanel getMainViewPanel() {
        return mainViewPanel;
    }
    

    // Main Menu
    public JButton getMainViewBtn() {
        return mainViewBtn;
    }
    public JButton getMakeTransacBtn() {
        return makeTransacBtn;
    }
    public JButton getGenReportsBtn() {
        return genReportsBtn;
    }
    public JButton getExitBtn() {
        return exitBtn;
    }

    // Main View
    public JButton getExecuteQueryMainViewBtn() {
        return executeQueryMainViewBtn;
    }
    
    public JComboBox<String> getTablesMainViewComboBox() {
        return tablesMainViewComboBox;
    }
    
    public JTextArea getQueryMainViewTxtArea() {
        return queryMainViewTxtArea;
    }
    
    public JButton getMainViewMainMenuBtn() {
        return mainViewMainMenuBtn;
    }
    
    public JTable getMainViewTable() {
        return mainViewTable;
    }
    
    // Transactions
    
    // TRANSFER PLAYER
    public JPanel getMakeTransacPanel() {
        return makeTransacPanel;
    }
    
    public JButton getMainMenuTransacBtn() {
        return mainMenuTransacBtn;
    }
    public JButton getFinalTransferPlayerBtn() {
        return finalTransferPlayerBtn;
    }
    public JButton getFinalDissolveTeamBtn() {
        return finalDissolveTeamBtn;
    }
    public JButton getFinalAddSponsorTeamBtn() {
        return finalAddSponsorTeamBtn;
    }
    public JButton getFinalTeamsUpdateStatsBtn() {
        return finalTeamsUpdateStatsBtn;
    }
    
    public JComboBox<String> getPlayerTransferPlayerComboBox() {
        return playerTransferPlayerComboBox;
    }
    
    public JComboBox<String> getTeamTransferPlayerTransacComboBox() {
        return teamTransferPlayerTransacComboBox;
    }
    
    // public JComboBox<String> getTableChooserTransferPlayerComboBox() {
    //     return tableChooserTransferPlayerComboBox;
    // }
 
    public JTextField getYearTransferPlayerTxtField() {
        return yearTransferPlayerTxtField;
    }
    public JTextField getMonthTransferPlayerTxtField() {
        return monthTransferPlayerTxtField;
    }
    public JTextField getDayTransferPlayerTxtField() {
        return dayTransferPlayerTxtField;
    }
    
    // public JButton getRefreshTableTransferPlayerBtn() {
        //     return refreshTableTransferPlayerBtn;
        // }
    
    // DISSOLVE TEAM
    public JComboBox<String> getTeamTransferTeamDissolveComboBox() {
        return teamTransferTeamDissolveComboBox;
    }
    public JTextField getYearDissolveTeamTxtField() {
        return yearDissolveTeamTxtField;
    }
    public JTextField getMonthDissolveTeamTxtField() {
        return monthDissolveTeamTxtField;
    }
    public JTextField getDayDissolveTeamTxtField() {
        return dayDissolveTeamTxtField;
    }

    // SPONSOR ADD
    public JLabel getCurrentTeamSponsorLbl() {
        return currentTeamSponsorLbl;
    }
    public JTextField getYearSponsorAddTxtField() {
        return yearSponsorAddTxtField;
    }
    public JTextField getMonthSponsorAddTxtField() {
        return monthSponsorAddTxtField;
    }
    public JTextField getDaySponsorAddTxtField() {
        return daySponsorAddTxtField;
    }
    public JTextField getYearSponsorAddTxtField1() {
        return yearSponsorAddTxtField1;
    }
    public JTextField getMonthSponsorAddTxtField1() {
        return monthSponsorAddTxtField1;
    }
    public JTextField getDaySponsorAddTxtField1() {
        return daySponsorAddTxtField1;
    }
    public JSpinner getAddSponsorTeamSpinner() {
        return addSponsorTeamSpinner;
    }
    
    // UPDATE STATS 
    public JTextField getYearTeamsUpdateStatsTxtField() {
        return yearTeamsUpdateStatsTxtField;
    }
    public JTextField getMonthTeamsUpdateStatsTxtField() {
        return monthTeamsUpdateStatsTxtField;
    }
    public JTextField getDayTeamsUpdateStatsTxtField() {
        return dayTeamsUpdateStatsTxtField;
    }
    public JSpinner getTeamsUpdateStatsSpinner() {
        return teamsUpdateStatsSpinner;
    }
    
    public DefaultTableModel getMainViewTableModel() {
        return mainViewTableModel;
    }
    public void setMainViewTableModel(DefaultTableModel mainViewTableModel) {
        this.mainViewTableModel = mainViewTableModel;  
    }
    
    // Combo Box Models
    public DefaultComboBoxModel<String> getPlayersComboBoxModel() {
        return playersComboBoxModel;
    }
    public DefaultComboBoxModel<String> getTeamsComboBoxModel() {
        return teamsTransferPlayerComboBoxModel;
    }

    public JComboBox<String> getTeamsUpdateStatsComboBox() {
        return teamsUpdateStatsComboBox;
    }
    public JComboBox<String> getTeamsUpdateStatsComboBox2() {
        return teamsUpdateStatsComboBox2;
    }
    public JComboBox<String> getTeamsWinnerUpdateStatsComboBox() {
        return teamsWinnerUpdateStatsComboBox;
    }
    public DefaultComboBoxModel<String> getTeamsUpdateStatsComboBoxModel() {
        return teamsUpdateStatsComboBoxModel;
    }
    public DefaultComboBoxModel<String> getTeamsUpdateStatsComboBoxModel2() {
        return teamsUpdateStatsComboBoxModel2;
    }

    // Sponsor Add
    public JComboBox<String> getSponsorAddComboBox() {
        return sponsorAddComboBox;
    }
    public JComboBox<String> getTeamSponsorAddComboBox() {
        return teamSponsorAddComboBox;
    }

    public void updateComboBox(DefaultComboBoxModel<String> comboBox, List<String> items, String selectedItem) {
        comboBox.removeAllElements();
        comboBox.addAll(items);
        comboBox.setSelectedItem(selectedItem);
    }
    public void updateComboBox3(String item1, String item2) {
        teamsWinnerUpdateStatsComboBox.removeAllItems();
        teamsWinnerUpdateStatsComboBox.addItem(item1);
        teamsWinnerUpdateStatsComboBox.addItem(item2);
    }

    public void setPlayersComboBoxModel(ArrayList<String> playerNames) {
        playersComboBoxModel.removeAllElements();
        playersComboBoxModel.addAll(playerNames);
    }

    public void setTeamsComboBoxModel(ArrayList<String> teamNames) {
        teamsTransferPlayerComboBoxModel.removeAllElements();
        teamsDissolveTeamComboBoxModel.removeAllElements();
        teamsUpdateStatsComboBoxModel.removeAllElements();
        teamsUpdateStatsComboBoxModel2.removeAllElements();
        teamsWinnerUpdateStatsComboBoxModel.removeAllElements();
        teamSponsorAddComboBoxModel.removeAllElements();
    
        teamsTransferPlayerComboBoxModel.addAll(teamNames);
        teamsDissolveTeamComboBoxModel.addAll(teamNames);
        teamsUpdateStatsComboBoxModel.addAll(teamNames);
        teamsUpdateStatsComboBoxModel2.addAll(teamNames);
        teamsWinnerUpdateStatsComboBoxModel.addAll(teamNames);
        teamSponsorAddComboBoxModel.addAll(teamNames);
    }

    public void setSponsorsComboBoxModel(ArrayList<String> sponsorNames) {
        sponsorAddComboBoxModel.removeAllElements();

        sponsorAddComboBoxModel.addAll(sponsorNames);
    }
   

    public void addClickListener(ActionListener e) {
        this.mainViewBtn.addActionListener(e);
        this.makeTransacBtn.addActionListener(e);
        this.genReportsBtn.addActionListener(e);
        this.exitBtn.addActionListener(e);

        this.executeQueryMainViewBtn.addActionListener(e);
        this.mainViewMainMenuBtn.addActionListener(e);
        this.tablesMainViewComboBox.addActionListener(e);

        this.mainMenuTransacBtn.addActionListener(e);
        this.finalTransferPlayerBtn.addActionListener(e);

        this.finalDissolveTeamBtn.addActionListener(e);


        this.teamsUpdateStatsComboBox.addActionListener(e);
        this.teamsUpdateStatsComboBox2.addActionListener(e);
        this.teamsWinnerUpdateStatsComboBox.addActionListener(e);

        this.teamSponsorAddComboBox.addActionListener(e);
        this.finalAddSponsorTeamBtn.addActionListener(e);


        this.finalTeamsUpdateStatsBtn.addActionListener(e);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    private DefaultTableModel mainViewTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSpinner addSponsorTeamSpinner;
    private SpinnerNumberModel addSponsorTeamSpinnerModel;
    private JPanel bannerPanel;
    private JLabel currentTeamSponsorLbl;
    private JTextField dayDissolveTeamTxtField;
    private JTextField daySponsorAddTxtField;
    private JTextField daySponsorAddTxtField1;
    private JTextField dayTeamsUpdateStatsTxtField;
    private JTextField dayTransferPlayerTxtField;
    private JButton executeQueryMainViewBtn;
    private JButton exitBtn;
    private JButton finalAddSponsorTeamBtn;
    private JButton finalDissolveTeamBtn;
    private JButton finalTeamsUpdateStatsBtn;
    private JButton finalTransferPlayerBtn;
    private JButton genReportsBtn;
    private JButton genReportsMainMenuBtn;
    private JPanel genReportsPanel;
    private JTable genReportsTable;
    private JCheckBox jCheckBox1;
    private JComboBox<String> jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel3;
    private JLabel jLabel39;
    private JLabel jLabel4;
    private JLabel jLabel40;
    private JLabel jLabel41;
    private JLabel jLabel42;
    private JLabel jLabel43;
    private JLabel jLabel44;
    private JLabel jLabel45;
    private JLabel jLabel46;
    private JLabel jLabel47;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JPanel leftMakeTransacPanel;
    private JPanel lowerLeftPanel;
    private JPanel lowerMainViewPanel;
    private JPanel lowerPanel;
    private JPanel lowerRightPanel;
    private JPanel mainMainPanel;
    private JButton mainMenuTransacBtn;
    private JPanel mainPanel;
    private JButton mainViewBtn;
    private JButton mainViewMainMenuBtn;
    private JPanel mainViewPanel;
    private static JTable mainViewTable;
    private JButton makeTransacBtn;
    private JPanel makeTransacPanel;
    private JLabel menuLbl;
    private JTextField monthDissolveTeamTxtField;
    private JTextField monthSponsorAddTxtField;
    private JTextField monthSponsorAddTxtField1;
    private JTextField monthTeamsUpdateStatsTxtField;
    private JTextField monthTransferPlayerTxtField;
    private JComboBox<String> playerTransferPlayerComboBox;
    private DefaultComboBoxModel<String> playersComboBoxModel;
    private JTextArea queryMainViewTxtArea;
    private JPanel rightMakeTransacPanel;
    private JComboBox<String> sponsorAddComboBox;
    private DefaultComboBoxModel<String> sponsorAddComboBoxModel;
    private JComboBox<String> tablesMainViewComboBox;
    private DefaultComboBoxModel<String> tablesMainViewComBoxDefModel;
    private JComboBox<String> teamSponsorAddComboBox;
    private DefaultComboBoxModel<String> teamSponsorAddComboBoxModel;
    private JComboBox<String> teamTransferPlayerTransacComboBox;
    private DefaultComboBoxModel<String> teamsTransferPlayerComboBoxModel;
    private JComboBox<String> teamTransferTeamDissolveComboBox;
    private DefaultComboBoxModel<String> teamsDissolveTeamComboBoxModel;
    private JComboBox<String> teamsUpdateStatsComboBox;
    private DefaultComboBoxModel<String> teamsUpdateStatsComboBoxModel;
    private JComboBox<String> teamsUpdateStatsComboBox2;
    private DefaultComboBoxModel<String> teamsUpdateStatsComboBoxModel2;
    private JSpinner teamsUpdateStatsSpinner;
    private SpinnerNumberModel teamsUpdateStatsSpinnerModel;
    private JComboBox<String> teamsWinnerUpdateStatsComboBox;
    private DefaultComboBoxModel<String> teamsWinnerUpdateStatsComboBoxModel;
    private JPanel transferPlayerPanel;
    private JPanel upperMainViewPanel;
    private JTextField yearDissolveTeamTxtField;
    private JComboBox<String> yearGenReportsComboBox;
    private JTextField yearSponsorAddTxtField;
    private JTextField yearSponsorAddTxtField1;
    private JTextField yearTeamsUpdateStatsTxtField;
    private JTextField yearTransferPlayerTxtField;
    // End of variables declaration//GEN-END:variables
    private DefaultComboBoxModel<String> playerTransferDefaultComboBoxModel;
}
