/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ccinfom.group5.esports_app.view;

import ccinfom.group5.esports_app.utils.GeneralUtil;
import javax.swing.JButton;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author Sean Kyle
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        System.out.println(mainViewTableModel.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        mainMainPanel = new JPanel();
        mainPanel = new JPanel();
        bannerPanel = new JPanel();
        jLabel1 = new JLabel();
        lowerPanel = new JPanel();
        lowerLeftPanel = new JPanel();
        menuLbl = new JLabel();
        mainViewBtn = new JButton();
        makeTransacBtn = new JButton();
        genReportsBtn = new JButton();
        exitBtn = new JButton();
        lowerRightPanel = new JPanel();
        mainViewPanel = new JPanel();
        upperMainViewPanel = new JPanel();
        jScrollPane1 = new JScrollPane();
        String[] columnNames = {"Column1", "Column2"};
        Object[][] data = {
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data1", "Data2"},
            {"Data3", "Data4"}
        };

        mainViewTableModel = new DefaultTableModel(data, columnNames);
        mainViewTable = new JTable();
        lowerMainViewPanel = new JPanel();
        mainViewMainMenuBtn = new JButton();
        tablesMainViewComboBox = new JComboBox<>();
        mainViewMakeTransacBtn = new JButton();
        executeQueryMainViewBtn = new JButton();
        jScrollPane3 = new JScrollPane();
        queryMainViewTxtArea = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESports Tracker - Valorant");
        setPreferredSize(new Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        mainMainPanel.setLayout(new CardLayout());

        mainPanel.setBackground(new Color(255, 204, 51));
        mainPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        mainPanel.setPreferredSize(new Dimension(1280, 720));
        mainPanel.setLayout(new GridBagLayout());

        bannerPanel.setBackground(new Color(51, 102, 0));

        jLabel1.setFont(new Font("Berlin Sans FB Demi", 0, 45)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("ESports Tracker - Valorant");
        jLabel1.setPreferredSize(new Dimension(1280, 720));

        GroupLayout bannerPanelLayout = new GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(bannerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                .addContainerGap())
        );
        bannerPanelLayout.setVerticalGroup(bannerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(bannerPanel, gridBagConstraints);

        lowerPanel.setMinimumSize(new Dimension(400, 600));
        lowerPanel.setLayout(new GridBagLayout());

        lowerLeftPanel.setBackground(new Color(204, 204, 204));
        lowerLeftPanel.setLayout(new GridBagLayout());

        menuLbl.setFont(new Font("sansserif", 1, 24)); // NOI18N
        menuLbl.setHorizontalAlignment(SwingConstants.CENTER);
        menuLbl.setText("MENU");
        menuLbl.setPreferredSize(new Dimension(70, 28));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        lowerLeftPanel.add(menuLbl, gridBagConstraints);

        mainViewBtn.setFont(new Font("sansserif", 0, 16)); // NOI18N
        mainViewBtn.setText("Main View");
        mainViewBtn.setPreferredSize(new Dimension(135, 60));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(7, 10, 7, 10);
        lowerLeftPanel.add(mainViewBtn, gridBagConstraints);

        makeTransacBtn.setFont(new Font("sansserif", 0, 15)); // NOI18N
        makeTransacBtn.setText("Make Transactions");
        makeTransacBtn.setPreferredSize(mainViewBtn.getPreferredSize());
        makeTransacBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                makeTransacBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(7, 10, 7, 10);
        lowerLeftPanel.add(makeTransacBtn, gridBagConstraints);

        genReportsBtn.setFont(new Font("sansserif", 0, 16)); // NOI18N
        genReportsBtn.setText("Generate Reports");
        genReportsBtn.setPreferredSize(mainViewBtn.getPreferredSize());
        genReportsBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                genReportsBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.insets = new Insets(7, 10, 7, 10);
        lowerLeftPanel.add(genReportsBtn, gridBagConstraints);

        exitBtn.setFont(new Font("sansserif", 0, 18)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.setPreferredSize(new Dimension(72, 40));
        exitBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(75, 10, 75, 10);
        lowerLeftPanel.add(exitBtn, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        lowerPanel.add(lowerLeftPanel, gridBagConstraints);

        lowerRightPanel.setBackground(new Color(0, 255, 204));

        GroupLayout lowerRightPanelLayout = new GroupLayout(lowerRightPanel);
        lowerRightPanel.setLayout(lowerRightPanelLayout);
        lowerRightPanelLayout.setHorizontalGroup(lowerRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lowerRightPanelLayout.setVerticalGroup(lowerRightPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        lowerPanel.add(lowerRightPanel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        mainPanel.add(lowerPanel, gridBagConstraints);

        mainMainPanel.add(mainPanel, "mainmenu");
        mainPanel.getAccessibleContext().setAccessibleParent(mainMainPanel);

        upperMainViewPanel.setPreferredSize(new Dimension(1280, 400));

        jScrollPane1.setViewportBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new Dimension(1000, 470));
        jScrollPane1.setViewportView(mainViewTable);
        jScrollPane1.setWheelScrollingEnabled(false);

        mainViewTable.setModel(mainViewTableModel);
        mainViewTable.setPreferredSize(null);
        mainViewTable.setRequestFocusEnabled(false);
        mainViewTable.setRowSelectionAllowed(false);
        mainViewTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(mainViewTable);

        GroupLayout upperMainViewPanelLayout = new GroupLayout(upperMainViewPanel);
        upperMainViewPanel.setLayout(upperMainViewPanelLayout);
        upperMainViewPanelLayout.setHorizontalGroup(upperMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, upperMainViewPanelLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        upperMainViewPanelLayout.setVerticalGroup(upperMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(upperMainViewPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 365, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lowerMainViewPanel.setPreferredSize(new Dimension(1124, 270));

        mainViewMainMenuBtn.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        mainViewMainMenuBtn.setText("Main Menu");
        mainViewMainMenuBtn.setPreferredSize(new Dimension(89, 30));
        mainViewMainMenuBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                mainViewMainMenuBtnActionPerformed(evt);
            }
        });

        tablesMainViewComBoxDefModel = new DefaultComboBoxModel<String>();
        for (String tableName : GeneralUtil.getArrayTableNames()) {
            tablesMainViewComBoxDefModel.addElement(tableName);
        }
        tablesMainViewComboBox.setModel(tablesMainViewComBoxDefModel);
        tablesMainViewComboBox.setPreferredSize(new Dimension(200, 35));

        mainViewMakeTransacBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        mainViewMakeTransacBtn.setText("<html><div style='text-align: center;'>Make<br>Transactions</div></html>");
        mainViewMakeTransacBtn.setToolTipText("");
        mainViewMakeTransacBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                mainViewMakeTransacBtnActionPerformed(evt);
            }
        });

        executeQueryMainViewBtn.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        executeQueryMainViewBtn.setText("Execute Query");
        executeQueryMainViewBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                executeQueryMainViewBtnActionPerformed(evt);
            }
        });

        queryMainViewTxtArea.setColumns(20);
        queryMainViewTxtArea.setRows(5);
        jScrollPane3.setViewportView(queryMainViewTxtArea);

        GroupLayout lowerMainViewPanelLayout = new GroupLayout(lowerMainViewPanel);
        lowerMainViewPanel.setLayout(lowerMainViewPanelLayout);
        lowerMainViewPanelLayout.setHorizontalGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablesMainViewComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(executeQueryMainViewBtn, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                    .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 537, GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(mainViewMakeTransacBtn, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainViewMainMenuBtn, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        lowerMainViewPanelLayout.setVerticalGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lowerMainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(lowerMainViewPanelLayout.createSequentialGroup()
                        .addComponent(mainViewMainMenuBtn, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainViewMakeTransacBtn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablesMainViewComboBox, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(executeQueryMainViewBtn, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        GroupLayout mainViewPanelLayout = new GroupLayout(mainViewPanel);
        mainViewPanel.setLayout(mainViewPanelLayout);
        mainViewPanelLayout.setHorizontalGroup(mainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, mainViewPanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lowerMainViewPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(mainViewPanelLayout.createSequentialGroup()
                .addComponent(upperMainViewPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainViewPanelLayout.setVerticalGroup(mainViewPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(mainViewPanelLayout.createSequentialGroup()
                .addComponent(upperMainViewPanel, GroupLayout.PREFERRED_SIZE, 446, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lowerMainViewPanel, GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainMainPanel.add(mainViewPanel, "mainview");

        getContentPane().add(mainMainPanel);
        mainMainPanel.setBounds(0, 0, 1280, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void genReportsBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_genReportsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genReportsBtnActionPerformed

    private void makeTransacBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_makeTransacBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeTransacBtnActionPerformed

    private void mainViewMakeTransacBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mainViewMakeTransacBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainViewMakeTransacBtnActionPerformed

    private void mainViewMainMenuBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mainViewMainMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainViewMainMenuBtnActionPerformed

    private void executeQueryMainViewBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_executeQueryMainViewBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_executeQueryMainViewBtnActionPerformed

    public CardLayout getCardLayout() {
        return (CardLayout) mainMainPanel.getLayout();
    }
    public JPanel getMainMainPanel() {
        return mainMainPanel;
    }
    public JPanel getMainPanel() {
        return mainPanel;
    }
    public JPanel getMainViewPanel() {
        return mainViewPanel;
    }
    

    // Main Menu
    public JButton getMainViewBtn() {
        return mainViewBtn;
    }
    public JButton getMakeTransacBtn() {
        return makeTransacBtn;
    }
    public JButton getGenReportsBtn() {
        return genReportsBtn;
    }
    public JButton getExitBtn() {
        return exitBtn;
    }


    public JButton getExecuteQueryMainViewBtn() {
        return executeQueryMainViewBtn;
    }
    
    public JComboBox getTablesMainViewComboBox() {
        return tablesMainViewComboBox;
    }
    
    public JTextArea getQueryMainViewTxtArea() {
        return queryMainViewTxtArea;
    }
    
    public JButton getMainViewMainMenuBtn() {
        return mainViewMainMenuBtn;
    }
    
    public JTable getMainViewTable() {
        return mainViewTable;
    }
    public DefaultTableModel getMainViewTableModel() {
        return mainViewTableModel;
    }
    public void setMainViewTableModel(DefaultTableModel mainViewTableModel) {
        this.mainViewTableModel = mainViewTableModel;  
    }
    

    public void addClickListener(ActionListener e) {
        this.mainViewBtn.addActionListener(e);
        this.makeTransacBtn.addActionListener(e);
        this.genReportsBtn.addActionListener(e);
        this.exitBtn.addActionListener(e);

        this.executeQueryMainViewBtn.addActionListener(e);
        this.tablesMainViewComboBox.addActionListener(e);
    }

    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    private DefaultTableModel mainViewTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel bannerPanel;
    private JButton executeQueryMainViewBtn;
    private JButton exitBtn;
    private JButton genReportsBtn;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane3;
    private JPanel lowerLeftPanel;
    private JPanel lowerMainViewPanel;
    private JPanel lowerPanel;
    private JPanel lowerRightPanel;
    private JPanel mainMainPanel;
    private JPanel mainPanel;
    private JButton mainViewBtn;
    private JButton mainViewMainMenuBtn;
    private JButton mainViewMakeTransacBtn;
    private JPanel mainViewPanel;
    private static JTable mainViewTable;
    private JButton makeTransacBtn;
    private JLabel menuLbl;
    private JTextArea queryMainViewTxtArea;
    private JComboBox<String> tablesMainViewComboBox;
    private DefaultComboBoxModel<String> tablesMainViewComBoxDefModel;
    private JPanel upperMainViewPanel;
    // End of variables declaration//GEN-END:variables
}
