INSERT INTO companies (id, company_name)
VALUES 
(1, "Intel"),
(2, "Logitech"),
(3, "Nvidia"),
(4, "Red Bull"),
(5, "Corsair"),
(6, "Razer"),
(7, "HyperX"),
(8, "ASUS"),
(9, "Samsung"),
(10, "Alienware"),
(11, "Monster Energy"),
(12, "MSI"),
(13, "Twitch"),
(14, "SteelSeries"),
(15, "Acer"),
(16, "DXRacer"),
(17, "AMD"),
(18, "Secretlab"),
(19, "PepsiCo"),
(20, "Coca-Cola");